# Generated by Django 3.2.6 on 2021-08-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_invitation_is_formal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitation_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='is_formal',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='p_from',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='p_to',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='place',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='template',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
