# Generated by Django 3.2.6 on 2021-08-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20210808_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_date',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
