# Generated by Django 3.2.6 on 2021-08-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_alter_invitation_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invitation_date',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
