# Generated by Django 3.2.6 on 2021-08-18 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generator', '0010_customtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtemplate',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customtemplate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='customtemplate',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
