# Generated by Django 3.2.6 on 2021-08-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0013_alter_invitation_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='template_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.customtemplate'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='template',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('happy', 'Happy'), ('funny', 'Funny'), ('love', 'Love')], max_length=50),
        ),
    ]
